import { PERMISSIONS, Permission } from './permissions';
import { Role } from '@/types';

/**
 * Legacy Role to Permission Mapping
 * This is used to maintain backward compatibility with EMS roles
 * while the system transitions to full PBAC.
 */
export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
    ADMIN: [
        PERMISSIONS.SYSTEM_ADMIN,
        PERMISSIONS.ADMIN_DASHBOARD_VIEW,
        PERMISSIONS.ADMIN_AUDIT_VIEW,
        PERMISSIONS.ADMIN_RBAC_MANAGE,
        PERMISSIONS.ADMIN_WORKFLOW_CONFIG,
        PERMISSIONS.ADMIN_HEALTH_VIEW,
        PERMISSIONS.SETTINGS_VIEW,
        PERMISSIONS.SETTINGS_MANAGE,
        PERMISSIONS.BASE_DASHBOARD_VIEW,
    ],

    HR: [
        PERMISSIONS.EMPLOYEES_VIEW,
        PERMISSIONS.EMPLOYEES_CREATE,
        PERMISSIONS.EMPLOYEES_UPDATE,
        PERMISSIONS.EMPLOYEES_DELETE,
        PERMISSIONS.LEAVES_VIEW,
        PERMISSIONS.LEAVES_APPROVE,
        PERMISSIONS.LEAVES_REJECT,
        PERMISSIONS.ATTENDANCE_VIEW,
        PERMISSIONS.DEPARTMENTS_VIEW,
        PERMISSIONS.DEPARTMENTS_MANAGE,
        PERMISSIONS.ANALYTICS_HR,
        PERMISSIONS.STUDENT_PROFILE_READ,
        PERMISSIONS.STUDENT_PROFILE_CREATE,
        PERMISSIONS.STUDENT_PROFILE_CREATE,
        PERMISSIONS.STUDENT_PROFILE_UPDATE,
        PERMISSIONS.BASE_DASHBOARD_VIEW,
    ],

    MANAGER: [
        PERMISSIONS.EMPLOYEES_VIEW,
        PERMISSIONS.PROJECTS_VIEW,
        PERMISSIONS.PROJECTS_CREATE,
        PERMISSIONS.PROJECTS_UPDATE,
        PERMISSIONS.LEAVES_VIEW,
        PERMISSIONS.LEAVES_APPROVE,
        PERMISSIONS.LEAVES_REJECT,
        PERMISSIONS.ATTENDANCE_VIEW,
        PERMISSIONS.ANALYTICS_MANAGER,
        PERMISSIONS.STUDENT_PROFILE_READ,
        PERMISSIONS.BASE_DASHBOARD_VIEW,
    ],

    EMPLOYEE: [
        PERMISSIONS.EMPLOYEES_VIEW,
        PERMISSIONS.PROJECTS_VIEW,
        PERMISSIONS.LEAVES_VIEW,
        PERMISSIONS.LEAVES_APPLY,
        PERMISSIONS.ATTENDANCE_VIEW,
        PERMISSIONS.ATTENDANCE_MARK,
        PERMISSIONS.ANALYTICS_EMPLOYEE,
        PERMISSIONS.BASE_DASHBOARD_VIEW,
    ],

    HR_MANAGER: [
        PERMISSIONS.EMPLOYEES_VIEW,
        PERMISSIONS.EMPLOYEES_CREATE,
        PERMISSIONS.EMPLOYEES_UPDATE,
        PERMISSIONS.EMPLOYEES_DELETE,
        PERMISSIONS.LEAVES_VIEW,
        PERMISSIONS.LEAVES_APPROVE,
        PERMISSIONS.LEAVES_REJECT,
        PERMISSIONS.ATTENDANCE_VIEW,
        PERMISSIONS.DEPARTMENTS_VIEW,
        PERMISSIONS.DEPARTMENTS_MANAGE,
        PERMISSIONS.ANALYTICS_HR,
        PERMISSIONS.STUDENT_PROFILE_READ,
        PERMISSIONS.BASE_DASHBOARD_VIEW,
    ],

    // Specific IERS Roles (Future-proofing)
    FACULTY: [
        PERMISSIONS.EMPLOYEES_VIEW,
        PERMISSIONS.STUDENT_PROFILE_READ,
        PERMISSIONS.STUDENT_PROFILE_CREATE,
        PERMISSIONS.STUDENT_PROFILE_UPDATE,
        PERMISSIONS.ATTENDANCE_VIEW,
        PERMISSIONS.ANALYTICS_EMPLOYEE,
        PERMISSIONS.FACULTY_PROFILE_READ,
        PERMISSIONS.STUDENTS_ASSIGNED_VIEW,
        PERMISSIONS.RESEARCH_DIRECTORY_VIEW,
        PERMISSIONS.REPORTS_ACADEMIC_VIEW,
        PERMISSIONS.BASE_DASHBOARD_VIEW,
    ],

    STUDENT: [
        PERMISSIONS.STUDENT_PROFILE_READ,
        PERMISSIONS.ATTENDANCE_VIEW,
        PERMISSIONS.PHD_APPLY,
        PERMISSIONS.PHD_SUBMIT,
        PERMISSIONS.PHD_VIEW,
        PERMISSIONS.CALENDAR_VIEW,
        PERMISSIONS.NOTIFICATIONS_STUDENT_VIEW,
        PERMISSIONS.DOCUMENTS_STUDENT_UPLOAD,
        PERMISSIONS.DOCUMENTS_VIEW,
        PERMISSIONS.BASE_DASHBOARD_VIEW,
    ],

    // IERS-specific roles
    GUIDE: [
        PERMISSIONS.GUIDE_ACCEPT,
        PERMISSIONS.GUIDE_SCHOLARS_VIEW,
        PERMISSIONS.GUIDE_PROGRESS_SUBMIT,
        PERMISSIONS.THESIS_VIEW,
        PERMISSIONS.RAC_DECISION_VIEW,
        PERMISSIONS.FACULTY_PROFILE_READ,
        PERMISSIONS.STUDENTS_ASSIGNED_VIEW,
        PERMISSIONS.BASE_DASHBOARD_VIEW,
    ],
    DRC_MEMBER: [],
    RAC_MEMBER: [],
    RRC_MEMBER: [],
    ADJUDICATOR: [],
    PRINCIPAL: [],
    MANAGEMENT: [],
    DEPT_ADMIN: [],
    FINANCE: [],
    IQAC_MEMBER: [],
    DVV_VERIFIER: [],
    EXTERNAL_REVIEWER: [],
    PLACEMENT_OFFICER: [],
    RECRUITER: [],
    MENTOR: [],
};
